### ISSUE TITLE
pip install pelican-flickrtag install will crash if pelican is not installed before

### ISSUE THREAD

**Issue by gagath** [haum/pelican-flickrtag#2]
When installing this module from a `requirements.txt` file including the `pelican` requirement, the install script of this package will fail because it will try to load the Pelican Python module which is not installed at the install time:

```
Collecting pelican-flickrtag from git+git://github.com/haum/pelican-flickrtag.git@master#egg=pelican-flickrtag (from -r requirements.txt (line 22))
  Cloning git://github.com/haum/pelican-flickrtag.git (to master) to /tmp/pip-build-lE3vFR/pelican-flickrtag
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-lE3vFR/pelican-flickrtag/setup.py", line 12, in <module>
        import pelican_flickrtag
      File "pelican_flickrtag/__init__.py", line 8, in <module>
        from pelican_flickrtag.plugin import register
      File "pelican_flickrtag/plugin.py", line 13, in <module>
        from pelican import signals
    ImportError: No module named pelican
```

Idea to fix the bug: simply don't try to import the module in the `setup.py` script and everything will install smoothly then.

**Comment by matael** [comment]
may be we can also add pelican as a dependency

**Comment by gagath** [comment]
Already marked as a dependency in the `setup.py` :

``` python
requires = [
    'jinja2',
    'pelican',
]
```

Problem is that `setup.py`, which should be bare Python, imports the module, and only in order to retrieve the version.

Could be easily fixed by moving the version into a separate bare Python file with no fancy imports.

**Comment by matael** [comment]
Ok, I don't know what to say. It sounds wrong to use a bare python file just to hold the `__version__` definition but I don't see any better way to do it. @MicroJoe just do it if you think it's OK

**Comment by gagath** [comment]
Well, all the metadata inside the `__init__.py` file is not used at all in the package. As stated in [this SO post](http://stackoverflow.com/questions/17791481/creating-a-version-attribute-for-python-packages-without-getting-into-troubl), we better should generate the metadata from the `setup.py` script rather than importing it from the module.

Since all the metadata is present in the `setup.py` and is not used in the package, I'm removing all the metadata (data replication is useless) and fixing the version in the `setup.py`.
